### ISSUE TITLE
Build error on raspberry pi 3

### ISSUE THREAD

**Issue by dmooney65** [zbjornson/node-bswap#1]
Hi,

node-gyp is failing on raspberry pi3   gcc version 4.9.2

pi@raspberrypi:~/node-bswap $ npm install

> bswap@1.1.6 install /home/pi/node-bswap
> node-gyp rebuild

make: Entering directory '/home/pi/node-bswap/build'
  CXX(target) Release/obj.target/bswap/src/bswap.o
*** Error in `g++': double free or corruption (!prev): 0x01787780 ***
bswap.target.mk:96: recipe for target 'Release/obj.target/bswap/src/bswap.o' failed
make: *** [Release/obj.target/bswap/src/bswap.o] Aborted
make: Leaving directory '/home/pi/node-bswap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

Any ideas? Would love to use this module oin a pi project I'm working on

**Comment by zbjornson** [comment]
Hello! Thanks for pointing this out.

It's failing because the fast C++ implementation uses x86-specific code. I've never done any ARM programming, but it looks like the CPU in the pi3 supports similar instructions.

* For now, I think it will work to use `npm install --ignore-scripts bswap` to skip the C++ build (although I don't think you can persist/communicate "ignore-scripts" if it's a dependency in package.json).
* If you're using node 6.3.0 or later, you can use the reasonably fast C++ implementation there (`buffer.swap16/32/64`)
* I can work on either gracefully failing the C++ build if x86 isn't available and letting it fall back to the JS version; or look at supporting a vectorized ARM C++ implementation. Do you need a fast implementation?
